#pragma once
// ellipse_gallery.xaml.hpp — page-construction declaration for the `ellipse_gallery` page (the C++ analog of a .xaml.cs
// partial's generated factory). Bodyless on purpose: the #embed and the build_page call live in the
// sibling translation unit ellipse_gallery.xaml.cpp, so main.cpp depends only on this declaration.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"
#include "maui/xaml/xaml_loader.hpp" // xaml_load_options (the application/theme threading knob)

namespace examples::Views
{
    // options threads the loader knobs — most importantly the application pointer, so
    // {AppThemeBinding} resolves against the app's CURRENT requested theme and re-applies on
    // RequestedThemeChanged (defaulted: theme-static hydration, the old behavior).
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> ellipse_gallery_page(
        const maui::xaml::xaml_load_options& options = {});
} // namespace examples::Views
