// grouping_no_templates.xaml.cpp — implements examples::Views::grouping_no_templates_page() (declared in
// grouping_no_templates.xaml.hpp).
//
// LEGACY LOCAL TWIN (pre-migration): embeds the local Views/grouping_no_templates.xaml, which has not yet moved to the
// canonical shared pages dir (port/maui-reference/pages). Migration: move the markup there (adding
// x:Class per docs/AUTHORING.md), delete Views/grouping_no_templates.xaml, re-run `e2e.py gen`.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include "Views/grouping_no_templates.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line
    // embed is the canonical form (a #embed directive cannot live inside a macro body).
    constexpr unsigned char grouping_no_templates_xaml_bytes[] = {
#embed "grouping_no_templates.xaml"
    };
    constexpr maui::fixed_string grouping_no_templates_xaml{grouping_no_templates_xaml_bytes};
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> grouping_no_templates_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, grouping_no_templates_xaml>();
    }
} // namespace examples::Views
