// header_footer_template.xaml.cpp — implements examples::Views::header_footer_template_page() (declared in
// header_footer_template.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds the CANONICAL SHARED page
// port/maui-reference/pages/header_footer_template.xaml — the exact same bytes real .NET MAUI compiles via XamlC +
// code-behind (MauiReference.Pages.HeaderFooterTemplatePage) — and build_page hydrates it through the runtime
// loader into a fresh page_impl<no_view_model>. One file, two frameworks, zero divergence.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include "Views/header_footer_template.xaml.hpp"

#include <cstddef>
#include <string_view>

#include "ViewModels/photo_items.hpp"
#include "maui/controls/items/collection_view.hpp"
#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file, like a quoted
    // #include). The two-line embed is the canonical form (a #embed directive cannot live inside a
    // macro body — see fixed_string.hpp).
    constexpr unsigned char header_footer_template_xaml_bytes[] = {
#embed "../../../../maui-reference/pages/header_footer_template.xaml"
    };
    constexpr maui::fixed_string header_footer_template_xaml{header_footer_template_xaml_bytes};

    // Compile-time naming-triple lock: the embedded bytes must be a ContentPage whose x:Class matches
    // this page's key-derived MAUI partial class (the lint's runtime check, enforced by the compiler).
    template <std::size_t N> constexpr bool bytes_contain(const unsigned char (&hay)[N], std::string_view needle)
    {
        if (needle.empty() || N < needle.size())
        {
            return needle.empty();
        }
        for (std::size_t i = 0; i + needle.size() <= N; i++)
        {
            bool match = true;
            for (std::size_t j = 0; j < needle.size(); j++)
            {
                if (static_cast<char>(hay[i + j]) != needle[j])
                {
                    match = false;
                    break;
                }
            }
            if (match)
            {
                return true;
            }
        }
        return false;
    }
    static_assert(bytes_contain(header_footer_template_xaml_bytes, "<ContentPage"));
    static_assert(bytes_contain(header_footer_template_xaml_bytes,
                                "x:Class=\"MauiReference.Pages.HeaderFooterTemplatePage\""));
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> header_footer_template_page(
        const maui::xaml::xaml_load_options& options)
    {
        auto page = maui::build_page<maui::no_view_model, header_footer_template_xaml>(options);
        // Code-behind data assignment (the reflection-free analog of HeaderFooterTemplatePage.xaml.cs): give
        // the x:Name'd CollectionView the per-row photo items so the ItemTemplate's {Binding Image}/{Binding
        // Caption} paths resolve to each row's own image (cover1/oasis/photo), matching original MAUI.
        if (auto list = page->find<maui::controls::collection_view>("ItemsCV"))
        {
            list->set_items_source(examples::ViewModels::photo_items());
        }
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return page;
    }
} // namespace examples::Views
