#pragma once
// header_footer_grid_horizontal.xaml.hpp — page-construction declaration for the `header_footer_grid_horizontal`
// gallery twin (the C++ analog of a .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of
// header_footer_grid_horizontal.xaml and the build_page call live in the sibling translation unit
// header_footer_grid_horizontal.xaml.cpp, so main.cpp depends only on this declaration and never sees
// #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> header_footer_grid_horizontal_page();
} // namespace examples::Views
