#pragma once
// invalidate_brush.xaml.hpp — page-construction declaration for the `invalidate_brush` gallery twin (the C++ analog of
// a .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of invalidate_brush.xaml and the build_page
// call live in the sibling translation unit invalidate_brush.xaml.cpp, so main.cpp depends only on this declaration
// and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> invalidate_brush_page();
} // namespace examples::Views
