// invalidate_brush.xaml.cpp — implements examples::Views::invalidate_brush_page() (declared in
// invalidate_brush.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds invalidate_brush.xaml with #embed and build_page hydrates
// it through the runtime loader into a fresh page_impl<no_view_model>. This mirrors MAUI's .xaml/.xaml.cs
// split — markup mechanics stay out of main.cpp — and, with no external codegen step, cross-compiles to the
// iOS app bundle. The twin is purely structural (it carries any data inline via x:Array), so there is no
// view-model and no code-behind.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include "Views/invalidate_brush.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line embed
    // is the canonical form (a #embed directive cannot live inside a macro body — see fixed_string.hpp).
    constexpr unsigned char invalidate_brush_xaml_bytes[] = {
#embed "invalidate_brush.xaml"
    };
    constexpr maui::fixed_string invalidate_brush_xaml{invalidate_brush_xaml_bytes};
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> invalidate_brush_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, invalidate_brush_xaml>();
    }
} // namespace examples::Views
