// ios_slider_update_on_tap.xaml.cpp — implements examples::Views::ios_slider_update_on_tap_page() (declared in
// ios_slider_update_on_tap.xaml.hpp).
//
// LEGACY LOCAL TWIN (pre-migration): embeds the local Views/ios_slider_update_on_tap.xaml, which has not yet moved to
// the canonical shared pages dir (port/maui-reference/pages). Migration: move the markup there (adding x:Class per
// docs/AUTHORING.md), delete Views/ios_slider_update_on_tap.xaml, re-run `e2e.py gen`.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include "Views/ios_slider_update_on_tap.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line
    // embed is the canonical form (a #embed directive cannot live inside a macro body).
    constexpr unsigned char ios_slider_update_on_tap_xaml_bytes[] = {
#embed "ios_slider_update_on_tap.xaml"
    };
    constexpr maui::fixed_string ios_slider_update_on_tap_xaml{ios_slider_update_on_tap_xaml_bytes};
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> ios_slider_update_on_tap_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, ios_slider_update_on_tap_xaml>();
    }
} // namespace examples::Views
