#pragma once
// ios_first_responder.xaml.hpp — page-construction declaration for the `ios_first_responder` gallery twin (the C++
// analog of a .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of ios_first_responder.xaml and
// the build_page call live in the sibling translation unit ios_first_responder.xaml.cpp, so main.cpp depends only on
// this declaration and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> ios_first_responder_page();
} // namespace examples::Views
