#pragma once
// pan_gesture_events.xaml.hpp — page-construction declaration for the `pan_gesture_events` gallery twin (the C++ analog
// of a .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of pan_gesture_events.xaml and the
// build_page call live in the sibling translation unit pan_gesture_events.xaml.cpp, so main.cpp depends only on this
// declaration and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> pan_gesture_events_page();
} // namespace examples::Views
