#pragma once
// radio_button_group.xaml.hpp — page-construction declaration for the `radio_button_group` page (the C++ analog of a
// .xaml.cs partial's generated factory). Bodyless on purpose: the #embed and the build_page call live in the sibling
// translation unit radio_button_group.xaml.cpp, so main.cpp depends only on this declaration.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> radio_button_group_page();
} // namespace examples::Views
