#pragma once
// scroll_mode_test.xaml.hpp — page-construction declaration for the `scroll_mode_test` page (the C++ analog of a
// .xaml.cs partial's generated factory). Bodyless on purpose: the #embed and the build_page call live in the sibling
// translation unit scroll_mode_test.xaml.cpp, so main.cpp depends only on this declaration.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> scroll_mode_test_page();
} // namespace examples::Views
