// scroll_mode_test.xaml.cpp — implements examples::Views::scroll_mode_test_page() (declared in
// scroll_mode_test.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds the CANONICAL SHARED page
// port/maui-reference/pages/scroll_mode_test.xaml — the exact same bytes real .NET MAUI compiles via XamlC +
// code-behind (MauiReference.Pages.ScrollModeTestPage) — and build_page hydrates it through the runtime
// loader into a fresh page_impl<no_view_model>. One file, two frameworks, zero divergence.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include "Views/scroll_mode_test.xaml.hpp"

#include <cstddef>
#include <string_view>

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file, like a quoted
    // #include). The two-line embed is the canonical form (a #embed directive cannot live inside a
    // macro body — see fixed_string.hpp).
    constexpr unsigned char scroll_mode_test_xaml_bytes[] = {
#embed "../../../../maui-reference/pages/scroll_mode_test.xaml"
    };
    constexpr maui::fixed_string scroll_mode_test_xaml{scroll_mode_test_xaml_bytes};

    // Compile-time naming-triple lock: the embedded bytes must be a ContentPage whose x:Class matches
    // this page's key-derived MAUI partial class (the lint's runtime check, enforced by the compiler).
    template <std::size_t N> constexpr bool bytes_contain(const unsigned char (&hay)[N], std::string_view needle)
    {
        if (needle.empty() || N < needle.size())
        {
            return needle.empty();
        }
        for (std::size_t i = 0; i + needle.size() <= N; i++)
        {
            bool match = true;
            for (std::size_t j = 0; j < needle.size(); j++)
            {
                if (static_cast<char>(hay[i + j]) != needle[j])
                {
                    match = false;
                    break;
                }
            }
            if (match)
            {
                return true;
            }
        }
        return false;
    }
    static_assert(bytes_contain(scroll_mode_test_xaml_bytes, "<ContentPage"));
    static_assert(bytes_contain(scroll_mode_test_xaml_bytes, "x:Class=\"MauiReference.Pages.ScrollModeTestPage\""));
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> scroll_mode_test_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, scroll_mode_test_xaml>();
    }
} // namespace examples::Views
