// selection_command_param.xaml.cpp — implements examples::Views::selection_command_param_page() (declared in
// selection_command_param.xaml.hpp).
//
// LEGACY LOCAL TWIN (pre-migration): embeds the local Views/selection_command_param.xaml, which has not yet moved to
// the canonical shared pages dir (port/maui-reference/pages). Migration: move the markup there (adding x:Class per
// docs/AUTHORING.md), delete Views/selection_command_param.xaml, re-run `e2e.py gen`.
//
// GENERATED by port/tools/e2e/e2e.py gen — do not edit by hand; re-run the generator instead.

#include "Views/selection_command_param.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line
    // embed is the canonical form (a #embed directive cannot live inside a macro body).
    constexpr unsigned char selection_command_param_xaml_bytes[] = {
#embed "selection_command_param.xaml"
    };
    constexpr maui::fixed_string selection_command_param_xaml{selection_command_param_xaml_bytes};
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> selection_command_param_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, selection_command_param_xaml>();
    }
} // namespace examples::Views
