#pragma once
// varied_size_selector.xaml.hpp — page-construction declaration for the `varied_size_selector` gallery twin (the C++
// analog of a .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of varied_size_selector.xaml and
// the build_page call live in the sibling translation unit varied_size_selector.xaml.cpp, so main.cpp depends only on
// this declaration and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> varied_size_selector_page();
} // namespace examples::Views
