// web_view.xaml.cpp — implements examples::Views::web_view_page() (declared in web_view.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds web_view.xaml with #embed and build_page hydrates
// it through the runtime loader into a fresh page_impl<no_view_model>. This mirrors MAUI's .xaml/.xaml.cs
// split — markup mechanics stay out of main.cpp — and, with no external codegen step, cross-compiles to the
// iOS app bundle. The twin is purely structural (it carries any data inline via x:Array), so there is no
// view-model and no code-behind.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include "Views/web_view.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line embed
    // is the canonical form (a #embed directive cannot live inside a macro body — see fixed_string.hpp).
    constexpr unsigned char web_view_xaml_bytes[] = {
#embed "web_view.xaml"
    };
    constexpr maui::fixed_string web_view_xaml{web_view_xaml_bytes};
} // namespace

namespace examples::Views
{
    std::unique_ptr<maui::controls::content_page> web_view_page()
    {
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, web_view_xaml>();
    }
} // namespace examples::Views
