// GENERATED by port/tools/e2e/e2e.py gen — trivial code-behind partial for pages/gap_items_updating_scroll_mode.xaml. Do not edit: pages needing
// interactivity replace this file with a hand-written partial (drop the GENERATED marker line above so
// the generator leaves it alone) wiring handlers via x:Name fields per docs/AUTHORING.md.
namespace MauiReference.Pages;

public partial class GapItemsUpdatingScrollModePage : ContentPage
{
    public GapItemsUpdatingScrollModePage()
    {
        InitializeComponent();
    }
}
