// GENERATED by port/tools/e2e/e2e.py gen — trivial code-behind partial for pages/header_footer_grid_horizontal.xaml. Do not edit: pages needing
// interactivity replace this file with a hand-written partial (drop the GENERATED marker line above so
// the generator leaves it alone) wiring handlers via x:Name fields per docs/AUTHORING.md.
namespace MauiReference.Pages;

public partial class HeaderFooterGridHorizontalPage : ContentPage
{
    public HeaderFooterGridHorizontalPage()
    {
        InitializeComponent();
    }
}
