#!/usr/bin/env python3
"""Stamp the per-page compile-time-XAML wrappers for examples/gallery_xaml.

Every gallery twin lives as markup in Views/<name>.xaml. This tool generates, for each, the two
boilerplate translation units that turn it into a callable page factory (the C++ analog of the MAUI
.xaml.cs generated partial):

    Views/<name>.xaml.hpp   declares  examples::Views::<name>_page()
    Views/<name>.xaml.cpp   #embed "<name>.xaml" + build_page<no_view_model, <name>_xaml>()

and the single aggregator header main.cpp consumes:

    Views/gallery_pages.hpp   includes every .xaml.hpp + the MAUI_XAML_GALLERY_PAGES(X) X-macro list.

These are pure boilerplate fully derivable from the twin's file name (every twin is purely structural —
it carries its own inline data via x:Array, so no view-model or code-behind is needed). Run this after
adding/removing a Views/*.xaml twin; the generated files are checked in (NOT a build-time codegen step).

    python3 examples/gallery_xaml/tools/gen_pages.py

---- Embed modes (--embed-mode) --------------------------------------------------------------------

The default mode (`embed`) emits the .xaml.cpp TU with a `#embed "<name>.xaml"` directive — the
compiler-managed XAML path (C23 #embed, needs Clang 19+). This is what iOS / macOS / maccatalyst /
headless build, and it is the CHECKED-IN form of Views/<name>.xaml.cpp. **This mode is unchanged; do
not alter the checked-in TUs.**

The `bytes` mode instead reads each Views/<name>.xaml at generation time and emits its bytes as a
`constexpr unsigned char <name>_xaml_bytes[] = { 0x.., ... };` literal — the SAME fixed_string /
build_page NTTP path, but with no #embed. This exists for the **Android NDK**, whose bundled Clang (18
as of NDK 27) does NOT implement #embed, so the checked-in `#embed` TUs fail to preprocess there. The
byte-array form is plain C++23 and compiles on Clang 18. Because bytes-mode is Android-only, it MUST be
generated into a separate --out-dir (never into Views/, which would clobber the committed #embed TUs the
other backends need); the CMake android app-host target adds that dir to its sources. The shared
Views/<name>.xaml.hpp declarations + Views/gallery_pages.hpp X-macro are reused verbatim (bytes-mode
regenerates NEITHER), so the runtime string -> factory dispatch is single-sourced across both modes.

    # regenerate the Android bytes-mode TUs into the build tree (what the android app host compiles):
    python3 examples/gallery_xaml/tools/gen_pages.py --embed-mode=bytes --out-dir <build-dir>
"""
import argparse
import os
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
EXAMPLE = os.path.normpath(os.path.join(HERE, ".."))
VIEWS = os.path.join(EXAMPLE, "Views")

HPP = '''#pragma once
// {name}.xaml.hpp — page-construction declaration for the `{name}` gallery twin (the C++ analog of a
// .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of {name}.xaml and the build_page
// call live in the sibling translation unit {name}.xaml.cpp, so main.cpp depends only on this declaration
// and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> {name}_page();
}} // namespace examples::Views
'''

CPP = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds {name}.xaml with #embed and build_page hydrates
// it through the runtime loader into a fresh page_impl<no_view_model>. This mirrors MAUI's .xaml/.xaml.cs
// split — markup mechanics stay out of main.cpp — and, with no external codegen step, cross-compiles to the
// iOS app bundle. The twin is purely structural (it carries any data inline via x:Array), so there is no
// view-model and no code-behind.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line embed
    // is the canonical form (a #embed directive cannot live inside a macro body — see fixed_string.hpp).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''

# The Android bytes-mode analog of CPP: identical fixed_string / build_page NTTP path, but the markup
# arrives as an inlined `unsigned char[]` byte-array literal (read from the .xaml at generation time)
# instead of a `#embed` directive. This is plain C++23 — it compiles on the NDK's Clang 18, which does
# not implement #embed. Generated into an android-only --out-dir; it reuses the committed
# Views/{name}.xaml.hpp declaration and Views/gallery_pages.hpp X-macro (dispatch is single-sourced).
BYTES_CPP = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// ANDROID BYTES MODE (gen_pages.py --embed-mode=bytes): this TU is the NDK-buildable twin of the
// checked-in #embed form. The NDK's bundled Clang (18 as of NDK 27) does NOT implement C23 #embed, so the
// committed Views/{name}.xaml.cpp (which #embeds {name}.xaml) fails to preprocess there. Here the markup
// is instead inlined as a byte-array literal — read from Views/{name}.xaml at generation time — and fed
// into the SAME maui::fixed_string / maui::build_page compile-time-XAML path. Plain C++23; Clang-18 clean.
//
// GENERATED by tools/gen_pages.py --embed-mode=bytes — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, inlined as bytes (the #embed-into-array form, but literal so no #embed is needed).
    // Byte count == the .xaml file size with NO trailing NUL, so fixed_string's byte-array ctor deduces
    // fixed_string<file_size> — identical to what #embed would produce for the same file.
    constexpr unsigned char {name}_xaml_bytes[] = {{
{byte_rows}
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''


def _byte_rows(path, per_row=16):
    """Read `path` and format its bytes as indented, comma-separated `0xNN` rows.

    The literal reproduces the file EXACTLY (no trailing NUL added), so the resulting
    `unsigned char[]` has length == the file size — the same array #embed would synthesize, which
    fixed_string's byte-array ctor (M == N, no NUL) expects.
    """
    with open(path, "rb") as fh:
        data = fh.read()
    rows = []
    for i in range(0, len(data), per_row):
        chunk = data[i : i + per_row]
        rows.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    if not rows:
        # An empty .xaml would make a zero-length array (ill-formed) — emit a single NUL so the file at
        # least compiles; a real twin is never empty, this is just defensive.
        rows = ["        0x00,"]
    return "\n".join(rows)


def _write_shared(names):
    """Write the per-page .xaml.hpp declarations + the aggregator gallery_pages.hpp into Views/.

    These are backend-agnostic (no #embed, no bytes) and shared by BOTH embed modes, so they are always
    (re)generated in-place. Returns the list of files written (for clang-format normalization).
    """
    written = []
    for name in names:
        hpp = os.path.join(VIEWS, name + ".xaml.hpp")
        with open(hpp, "w") as fh:
            fh.write(HPP.format(name=name))
        written.append(hpp)

    includes = "\n".join(f'#include "Views/{n}.xaml.hpp"' for n in names)
    xmacro = " \\\n".join(f"    X({n})" for n in names)
    agg = f'''#pragma once
// gallery_pages.hpp — the single aggregator main.cpp's page switcher consumes. It (1) pulls in every
// per-page factory declaration so examples::Views::<name>_page() resolves, and (2) defines the
// MAUI_XAML_GALLERY_PAGES(X) X-macro — one X(<name>) per twin — so the runtime string -> compile-time
// factory dispatch is single-sourced (mirrors the builder gallery's MAUI_GALLERY_PAGES in gallery_host.hpp).
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator when twins change.

{includes}

// One X(<name>) per twin; main.cpp expands it to a `selected == "<name>"` -> <name>_page() dispatch.
#define MAUI_XAML_GALLERY_PAGES(X) \\
{xmacro}
'''
    agg_path = os.path.join(VIEWS, "gallery_pages.hpp")
    with open(agg_path, "w") as fh:
        fh.write(agg)
    written.append(agg_path)
    return written


def _write_embed_cpps(names):
    """Write the checked-in #embed .xaml.cpp TUs into Views/ (default mode). Returns files written."""
    written = []
    for name in names:
        cpp = os.path.join(VIEWS, name + ".xaml.cpp")
        with open(cpp, "w") as fh:
            fh.write(CPP.format(name=name))
        written.append(cpp)
    return written


def _write_bytes_cpps(names, out_dir):
    """Write the android bytes-mode .xaml.cpp TUs into out_dir. Returns files written.

    Only the .cpp TUs are emitted here; the .hpp declarations + gallery_pages.hpp are the shared,
    in-Views/ files (this mode reuses them). out_dir must NOT be Views/ (guarded by the caller) so the
    committed #embed TUs the other backends need are never clobbered.
    """
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name in names:
        xaml = os.path.join(VIEWS, name + ".xaml")
        cpp = os.path.join(out_dir, name + ".xaml.cpp")
        with open(cpp, "w") as fh:
            fh.write(BYTES_CPP.format(name=name, byte_rows=_byte_rows(xaml)))
        written.append(cpp)
    return written


def _clang_format(files):
    # Normalize to the repo's .clang-format (the aggregator's X-macro needs the backslash-alignment
    # clang-format applies; emitting it here keeps the generated files gate-clean without a hand-edit).
    # Bytes-mode TUs are left UNFORMATTED: they are giant machine-generated byte arrays in an out-of-tree
    # build dir (never committed, never linted), and running clang-format over 59 multi-KB arrays is slow
    # for no benefit.
    clang_format = shutil.which("clang-format")
    if clang_format:
        subprocess.run([clang_format, "-i", "--style=file", *files], check=True)
    else:
        print("WARNING: clang-format not found — generated files may need formatting before the gate")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--embed-mode",
        choices=("embed", "bytes"),
        default="embed",
        help="embed: #embed the .xaml (default; the checked-in iOS/macOS/headless form). "
        "bytes: inline the .xaml bytes as an unsigned char[] literal (Android NDK Clang-18, needs --out-dir).",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory for the .cpp TUs in --embed-mode=bytes (required for bytes; MUST NOT be Views/).",
    )
    args = parser.parse_args()

    names = sorted(
        os.path.splitext(f)[0]
        for f in os.listdir(VIEWS)
        if f.endswith(".xaml") and not f.endswith((".xaml.hpp", ".xaml.cpp"))
    )

    if args.embed_mode == "bytes":
        if not args.out_dir:
            parser.error("--embed-mode=bytes requires --out-dir (an android-only build location, not Views/)")
        out_dir = os.path.abspath(args.out_dir)
        if os.path.normpath(out_dir) == os.path.normpath(VIEWS):
            parser.error("--out-dir must NOT be Views/ (it would clobber the committed #embed TUs)")
        # bytes-mode emits ONLY the .cpp TUs; the .hpp + gallery_pages.hpp are the shared in-Views/ files.
        written = _write_bytes_cpps(names, out_dir)
        print(f"generated {len(names)} bytes-mode pages (.xaml.cpp) into {out_dir}")
        print("default page present:", "value_controls" in names)
        return

    # embed mode (default): regenerate the checked-in .hpp + #embed .cpp + gallery_pages.hpp in-place.
    written = _write_embed_cpps(names) + _write_shared(names)
    _clang_format(written)
    print(f"generated {len(names)} pages (.hpp + .cpp) + gallery_pages.hpp")
    print("default page present:", "value_controls" in names)


if __name__ == "__main__":
    main()
