#!/usr/bin/env python3
"""Stamp the per-page compile-time-XAML wrappers for examples/gallery_xaml.

Every gallery twin lives as markup in Views/<name>.xaml. This tool generates, for each, the two
boilerplate translation units that turn it into a callable page factory (the C++ analog of the MAUI
.xaml.cs generated partial):

    Views/<name>.xaml.hpp   declares  examples::Views::<name>_page()
    Views/<name>.xaml.cpp   #embed "<name>.xaml" + build_page<no_view_model, <name>_xaml>()

and the single aggregator header main.cpp consumes:

    Views/gallery_pages.hpp   includes every .xaml.hpp + the MAUI_XAML_GALLERY_PAGES(X) X-macro list.

These are pure boilerplate fully derivable from the twin's file name (every twin is purely structural —
it carries its own inline data via x:Array, so no view-model or code-behind is needed). Run this after
adding/removing a Views/*.xaml twin; the generated files are checked in (NOT a build-time codegen step).

    python3 examples/gallery_xaml/tools/gen_pages.py
"""
import os
import shutil
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
EXAMPLE = os.path.normpath(os.path.join(HERE, ".."))
VIEWS = os.path.join(EXAMPLE, "Views")

HPP = '''#pragma once
// {name}.xaml.hpp — page-construction declaration for the `{name}` gallery twin (the C++ analog of a
// .xaml.cs partial's generated factory). Bodyless on purpose: the #embed of {name}.xaml and the build_page
// call live in the sibling translation unit {name}.xaml.cpp, so main.cpp depends only on this declaration
// and never sees #embed/build_page. The twin is purely structural — no view-model.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> {name}_page();
}} // namespace examples::Views
'''

CPP = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds {name}.xaml with #embed and build_page hydrates
// it through the runtime loader into a fresh page_impl<no_view_model>. This mirrors MAUI's .xaml/.xaml.cs
// split — markup mechanics stay out of main.cpp — and, with no external codegen step, cross-compiles to the
// iOS app bundle. The twin is purely structural (it carries any data inline via x:Array), so there is no
// view-model and no code-behind.
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line embed
    // is the canonical form (a #embed directive cannot live inside a macro body — see fixed_string.hpp).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''


def main():
    names = sorted(
        os.path.splitext(f)[0]
        for f in os.listdir(VIEWS)
        if f.endswith(".xaml") and not f.endswith((".xaml.hpp", ".xaml.cpp"))
    )
    written = []
    for name in names:
        hpp = os.path.join(VIEWS, name + ".xaml.hpp")
        cpp = os.path.join(VIEWS, name + ".xaml.cpp")
        with open(hpp, "w") as fh:
            fh.write(HPP.format(name=name))
        with open(cpp, "w") as fh:
            fh.write(CPP.format(name=name))
        written += [hpp, cpp]

    includes = "\n".join(f'#include "Views/{n}.xaml.hpp"' for n in names)
    xmacro = " \\\n".join(f"    X({n})" for n in names)
    agg = f'''#pragma once
// gallery_pages.hpp — the single aggregator main.cpp's page switcher consumes. It (1) pulls in every
// per-page factory declaration so examples::Views::<name>_page() resolves, and (2) defines the
// MAUI_XAML_GALLERY_PAGES(X) X-macro — one X(<name>) per twin — so the runtime string -> compile-time
// factory dispatch is single-sourced (mirrors the builder gallery's MAUI_GALLERY_PAGES in gallery_host.hpp).
//
// GENERATED by tools/gen_pages.py — do not edit by hand; re-run the generator when twins change.

{includes}

// One X(<name>) per twin; main.cpp expands it to a `selected == "<name>"` -> <name>_page() dispatch.
#define MAUI_XAML_GALLERY_PAGES(X) \\
{xmacro}
'''
    agg_path = os.path.join(VIEWS, "gallery_pages.hpp")
    with open(agg_path, "w") as fh:
        fh.write(agg)
    written.append(agg_path)

    # Normalize to the repo's .clang-format (the aggregator's X-macro needs the backslash-alignment
    # clang-format applies; emitting it here keeps the generated files gate-clean without a hand-edit).
    clang_format = shutil.which("clang-format")
    if clang_format:
        subprocess.run([clang_format, "-i", "--style=file", *written], check=True)
    else:
        print("WARNING: clang-format not found — generated files may need formatting before the gate")

    print(f"generated {len(names)} pages (.hpp + .cpp) + gallery_pages.hpp")
    print("default page present:", "value_controls" in names)


if __name__ == "__main__":
    main()
