#!/usr/bin/env python3
"""e2e.py — THE unified tool for the MAUI-vs-C++-port end-to-end verification loop.

One entrypoint, subcommands for every deterministic step of the loop (see
port/maui-reference/docs/VERIFICATION_LOOP.md for the full 10-step protocol this tool serves, and
README.md next to this file for per-subcommand usage). It progressively absorbs the legacy script zoo
under port/cpp/tools/parity/ and port/cpp/docs/comparison/tools/ — each legacy script is deleted once
its subcommand replaces it.

Data model (the "naming triple", lint-enforced): a page key like `activity_indicator` maps to
    port/maui-reference/pages/activity_indicator.xaml            (THE canonical shared markup)
    x:Class="MauiReference.Pages.ActivityIndicatorPage"          (MAUI code-behind partial class)
    examples::Views::activity_indicator_page()                   (C++ port page factory)
The same .xaml bytes are compiled by real MAUI (XamlC + code-behind) and #embed-ded by the port's
gallery_xaml app — one file, two frameworks, zero divergence.

Subcommands implemented so far:
    gen     regenerate the C++ TU wrappers (.xaml.hpp/.xaml.cpp + gallery_pages.hpp aggregator) AND the
            trivial MAUI code-behind partials from pages/*.xaml. Transitional: pages still living as
            local gallery_xaml/Views/*.xaml twins keep their old-style TUs; a shared page SUPERSEDES a
            same-named local twin (migration = add pages/<k>.xaml, delete Views/<k>.xaml, re-run gen).
    lint    authoring-rule checks over pages/*.xaml + manifest.json (see AUTHORING.md).
    keys    print the canonical page-key set (from pages/*.xaml [+ legacy Views twins during migration]).
    capture screenshot capture (maccatalyst implemented; ios/android/appkit still on the legacy scripts).
            maui -> port/maui-reference/captures/<platform>/<key>_<theme>.png; cpp/xaml -> the existing
            docs/comparison/captures layout. The frozen captures/*/maui tree is never written.
    board   rescan captures -> refresh comparison.json screenshot paths (maui resolves dual-root: the new
            maui-reference tree first, the frozen historical tree as fallback) -> regenerate README.md.
    pixel   SSIM + diff%% scorer for parity ruling 5's four comparisons (MAUI vs cpp -> "pixel", MAUI vs
            xaml -> "pixel_xaml", light+dark) into comparison.json. Needs Pillow + numpy.
    consistency   mechanical cpp<->xaml cross-check: flags any page marked green vs MAUI on BOTH
            columns (sonnet + sonnet_xaml) whose cpp and xaml screenshots nonetheless differ from each
            other by SSIM/diff%% — the self-contradiction ruling 5 review batches must not produce.
            Writes a "consistency" slot; see docs/VERIFICATION_LOOP.md "Review methodology" for the
            prompt rule this backs up.

Planned (see README): record, vision, catalog, judge; ios/android/appkit capture.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time

# ---------------------------------------------------------------- paths -----------------------------
HERE = os.path.dirname(os.path.abspath(__file__))           # port/tools/e2e
PORT = os.path.normpath(os.path.join(HERE, "..", ".."))     # port/
REF = os.path.join(PORT, "maui-reference")
PAGES = os.path.join(REF, "pages")                          # canonical shared XAML
MANIFEST = os.path.join(PAGES, "manifest.json")
APP_PAGES = os.path.join(REF, "app", "Pages")               # MAUI code-behind partials
REF_CAPTURES = os.path.join(REF, "captures")                # MAUI ground-truth screenshots (mutable)
CPP = os.path.join(PORT, "cpp")
GALLERY_XAML = os.path.join(CPP, "examples", "gallery_xaml")
VIEWS = os.path.join(GALLERY_XAML, "Views")                 # C++ TU wrappers (+ legacy local twins)
COMP = os.path.join(CPP, "docs", "comparison")              # the board (comparison.json + README)
COMP_JSON = os.path.join(COMP, "comparison.json")

# #embed path from a TU in Views/ to the shared pages dir (resolved relative to the including file,
# like a quoted #include): Views -> gallery_xaml -> examples -> cpp -> port -> maui-reference/pages.
EMBED_REL = "../../../../maui-reference/pages"

GENERATED_MARK = "GENERATED by port/tools/e2e/e2e.py"


def pascal(key: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in key.split("_") if w)


def shared_keys() -> list[str]:
    if not os.path.isdir(PAGES):
        return []
    return sorted(os.path.splitext(f)[0] for f in os.listdir(PAGES) if f.endswith(".xaml"))


def legacy_keys() -> list[str]:
    """Local gallery_xaml/Views twins not yet migrated to the shared pages dir."""
    if not os.path.isdir(VIEWS):
        return []
    return sorted(
        os.path.splitext(f)[0]
        for f in os.listdir(VIEWS)
        if f.endswith(".xaml") and not f.endswith((".xaml.hpp", ".xaml.cpp"))
    )


def all_keys() -> list[str]:
    return sorted(set(shared_keys()) | set(legacy_keys()))


def load_manifest() -> list[dict]:
    if not os.path.isfile(MANIFEST):
        return []
    with open(MANIFEST, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------- gen: C++ TU templates -------------
HPP = '''#pragma once
// {name}.xaml.hpp — page-construction declaration for the `{name}` page (the C++ analog of a .xaml.cs
// partial's generated factory). Bodyless on purpose: the #embed and the build_page call live in the
// sibling translation unit {name}.xaml.cpp, so main.cpp depends only on this declaration.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"
#include "maui/xaml/xaml_loader.hpp" // xaml_load_options (the application/theme threading knob)

namespace examples::Views
{{
    // options threads the loader knobs — most importantly the application pointer, so
    // {{AppThemeBinding}} resolves against the app's CURRENT requested theme and re-applies on
    // RequestedThemeChanged (defaulted: theme-static hydration, the old behavior).
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> {name}_page(
        const maui::xaml::xaml_load_options& options = {{}});
}} // namespace examples::Views
'''

# Shared-page TU: #embed points OUT of the repo's cpp tree at the canonical maui-reference/pages file,
# and static_asserts compile-time-lock the naming triple (file <-> key <-> x:Class).
CPP_SHARED = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds the CANONICAL SHARED page
// port/maui-reference/pages/{name}.xaml — the exact same bytes real .NET MAUI compiles via XamlC +
// code-behind (MauiReference.Pages.{pascal}Page) — and build_page hydrates it through the runtime
// loader into a fresh page_impl<no_view_model>. One file, two frameworks, zero divergence.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include <cstddef>
#include <string_view>

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file, like a quoted
    // #include). The two-line embed is the canonical form (a #embed directive cannot live inside a
    // macro body — see fixed_string.hpp).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{embed_rel}/{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};

    // Compile-time naming-triple lock: the embedded bytes must be a ContentPage whose x:Class matches
    // this page's key-derived MAUI partial class (the lint's runtime check, enforced by the compiler).
    template <std::size_t N>
    constexpr bool bytes_contain(const unsigned char (&hay)[N], std::string_view needle)
    {{
        if (needle.empty() || N < needle.size())
        {{
            return needle.empty();
        }}
        for (std::size_t i = 0; i + needle.size() <= N; i++)
        {{
            bool match = true;
            for (std::size_t j = 0; j < needle.size(); j++)
            {{
                if (static_cast<char>(hay[i + j]) != needle[j])
                {{
                    match = false;
                    break;
                }}
            }}
            if (match)
            {{
                return true;
            }}
        }}
        return false;
    }}
    static_assert(bytes_contain({name}_xaml_bytes, "<ContentPage"));
    static_assert(bytes_contain({name}_xaml_bytes, "x:Class=\\"MauiReference.Pages.{pascal}Page\\""));
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page(const maui::xaml::xaml_load_options& options)
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>(options);
    }}
}} // namespace examples::Views
'''

# Legacy-twin TU: unchanged from the retired gen_pages.py — local Views/<name>.xaml, no x:Class lock
# (legacy twins predate the shared-page naming triple). Deleted per page as migration proceeds.
CPP_LEGACY = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// LEGACY LOCAL TWIN (pre-migration): embeds the local Views/{name}.xaml, which has not yet moved to the
// canonical shared pages dir (port/maui-reference/pages). Migration: move the markup there (adding
// x:Class per docs/AUTHORING.md), delete Views/{name}.xaml, re-run `e2e.py gen`.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line
    // embed is the canonical form (a #embed directive cannot live inside a macro body).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page(const maui::xaml::xaml_load_options& options)
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>(options);
    }}
}} // namespace examples::Views
'''

BYTES_CPP = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// ANDROID BYTES MODE (e2e.py gen --embed-mode=bytes): the NDK-buildable twin of the checked-in #embed
// form. The NDK's bundled Clang (18 as of NDK 27) does NOT implement C23 #embed, so the markup is
// inlined as a byte-array literal — read from the page's .xaml at generation time — and fed into the
// SAME maui::fixed_string / maui::build_page compile-time-XAML path. Plain C++23; Clang-18 clean.
//
// {mark} gen --embed-mode=bytes — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, inlined as bytes (the #embed-into-array form, but literal so no #embed is needed).
    // Byte count == the .xaml file size with NO trailing NUL, so fixed_string's byte-array ctor deduces
    // fixed_string<file_size> — identical to what #embed would produce for the same file.
    constexpr unsigned char {name}_xaml_bytes[] = {{
{byte_rows}
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page(const maui::xaml::xaml_load_options& options)
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>(options);
    }}
}} // namespace examples::Views
'''

AGGREGATOR = '''#pragma once
// gallery_pages.hpp — the single aggregator main.cpp's page switcher consumes. It (1) pulls in every
// per-page factory declaration so examples::Views::<name>_page() resolves, and (2) defines the
// MAUI_XAML_GALLERY_PAGES(X) X-macro — one X(<name>) per page — so the runtime string -> compile-time
// factory dispatch is single-sourced (mirrors the builder gallery's MAUI_GALLERY_PAGES).
//
// {mark} gen — do not edit by hand; re-run the generator when pages change.

{includes}

// One X(<name>) per page; main.cpp expands it to a `selected == "<name>"` -> <name>_page() dispatch.
#define MAUI_XAML_GALLERY_PAGES(X) \\
{xmacro}
'''

CODEBEHIND = '''// {mark} gen — trivial code-behind partial for pages/{name}.xaml. Do not edit: pages needing
// interactivity replace this file with a hand-written partial (drop the GENERATED marker line above so
// the generator leaves it alone) wiring handlers via x:Name fields per docs/AUTHORING.md.
namespace MauiReference.Pages;

public partial class {pascal}Page : ContentPage
{{
    public {pascal}Page()
    {{
        InitializeComponent();
    }}
}}
'''


def _byte_rows(path: str, per_row: int = 16) -> str:
    with open(path, "rb") as fh:
        data = fh.read()
    rows = []
    for i in range(0, len(data), per_row):
        chunk = data[i : i + per_row]
        rows.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(rows) if rows else "        0x00,"


def _clang_format(files: list[str]) -> None:
    clang_format = shutil.which("clang-format")
    if clang_format and files:
        subprocess.run([clang_format, "-i", "--style=file", *files], check=True)
    elif files:
        print("WARNING: clang-format not found — generated files may need formatting before the gate")


def cmd_gen(args: argparse.Namespace) -> int:
    shared = shared_keys()
    legacy = [k for k in legacy_keys() if k not in shared]
    names = sorted(set(shared) | set(legacy))
    if not names:
        print("no pages found (neither shared pages/ nor legacy Views twins) — nothing to generate")
        return 0

    if args.embed_mode == "bytes":
        if not args.out_dir:
            print("error: --embed-mode=bytes requires --out-dir (an android-only build dir, not Views/)")
            return 2
        out_dir = os.path.abspath(args.out_dir)
        if os.path.normpath(out_dir) == os.path.normpath(VIEWS):
            print("error: --out-dir must NOT be Views/ (it would clobber the committed #embed TUs)")
            return 2
        os.makedirs(out_dir, exist_ok=True)
        for name in names:
            src = os.path.join(PAGES if name in shared else VIEWS, name + ".xaml")
            with open(os.path.join(out_dir, name + ".xaml.cpp"), "w") as fh:
                fh.write(BYTES_CPP.format(name=name, byte_rows=_byte_rows(src), mark=GENERATED_MARK))
        print(f"generated {len(names)} bytes-mode TUs into {out_dir} "
              f"({len(shared)} shared, {len(legacy)} legacy)")
        return 0

    written = []
    # C++ TU wrappers (shared pages get the x:Class-locked shared template; legacy twins the old one).
    for name in names:
        with open(os.path.join(VIEWS, name + ".xaml.hpp"), "w") as fh:
            fh.write(HPP.format(name=name, mark=GENERATED_MARK))
        template = CPP_SHARED if name in shared else CPP_LEGACY
        with open(os.path.join(VIEWS, name + ".xaml.cpp"), "w") as fh:
            fh.write(template.format(name=name, pascal=pascal(name), embed_rel=EMBED_REL, mark=GENERATED_MARK))
        written += [os.path.join(VIEWS, name + ".xaml.hpp"), os.path.join(VIEWS, name + ".xaml.cpp")]

    includes = "\n".join(f'#include "Views/{n}.xaml.hpp"' for n in names)
    xmacro = " \\\n".join(f"    X({n})" for n in names)
    agg = os.path.join(VIEWS, "gallery_pages.hpp")
    with open(agg, "w") as fh:
        fh.write(AGGREGATOR.format(includes=includes, xmacro=xmacro, mark=GENERATED_MARK))
    written.append(agg)
    _clang_format(written)

    # MAUI code-behind partials for shared pages (skip hand-written ones — no GENERATED marker).
    os.makedirs(APP_PAGES, exist_ok=True)
    cb_new, cb_kept = 0, 0
    for name in shared:
        cb = os.path.join(APP_PAGES, pascal(name) + "Page.xaml.cs")
        if os.path.isfile(cb):
            with open(cb, encoding="utf-8") as fh:
                if GENERATED_MARK not in fh.read():
                    cb_kept += 1
                    continue  # hand-written interactive partial — leave alone
        with open(cb, "w", encoding="utf-8") as fh:
            fh.write(CODEBEHIND.format(name=name, pascal=pascal(name), mark=GENERATED_MARK))
        cb_new += 1

    print(f"generated {len(names)} C++ TU pairs + gallery_pages.hpp "
          f"({len(shared)} shared, {len(legacy)} legacy) ; "
          f"MAUI code-behinds: {cb_new} generated, {cb_kept} hand-written kept")
    return 0


# ---------------------------------------------------------------- lint ------------------------------
# Event-ish attributes banned in shared XAML (interactivity lives in code-behind via x:Name, so the
# port — which has no event-attribute support — hydrates the identical static tree).
EVENT_ATTRS = (
    "Clicked|Pressed|Released|Tapped|TextChanged|ValueChanged|Toggled|CheckedChanged|SelectedIndexChanged|"
    "SelectionChanged|ItemSelected|ItemTapped|Scrolled|ScrollToRequested|Refreshing|SearchButtonPressed|"
    "DateSelected|TimeSelected|Completed|Unfocused|Focused|Loaded|Unloaded|Appearing|Disappearing|"
    "NavigatedTo|NavigatingFrom|NavigatedFrom|PositionChanged|CurrentItemChanged|RemainingItemsThresholdReached|"
    "SwipeStarted|SwipeChanging|SwipeEnded|DragStarting|DropCompleted|Navigating|Navigated"
)
EVENT_RE = re.compile(r"\b(?:" + EVENT_ATTRS + r')\s*=\s*"')
XCLASS_RE = re.compile(r'x:Class\s*=\s*"([^"]+)"')
X2006 = "http://schemas.microsoft.com/winfx/2006/xaml"


def cmd_lint(_args: argparse.Namespace) -> int:
    problems: list[str] = []
    shared = shared_keys()
    manifest = {row["key"]: row for row in load_manifest()}

    for key in shared:
        path = os.path.join(PAGES, key + ".xaml")
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        rel = os.path.relpath(path, PORT)

        m = EVENT_RE.search(text)
        if m:
            problems.append(f"{rel}: event attribute {m.group(0)!r} — banned; wire via x:Name + code-behind")
        m = XCLASS_RE.search(text)
        if not m:
            problems.append(f"{rel}: missing x:Class (required by the MAUI build)")
        elif m.group(1) != f"MauiReference.Pages.{pascal(key)}Page":
            problems.append(f"{rel}: x:Class={m.group(1)!r} != MauiReference.Pages.{pascal(key)}Page "
                            "(naming triple violated)")
        if X2006 in text:
            problems.append(f"{rel}: uses winfx/2006 x: namespace — standardize on winfx/2009 (AUTHORING.md)")
        if "<ContentPage" not in text:
            problems.append(f"{rel}: root element is not ContentPage")
        if key not in manifest:
            problems.append(f"{rel}: no row in pages/manifest.json")

    for key in manifest:
        if key not in shared:
            problems.append(f"manifest.json: row {key!r} has no pages/{key}.xaml file")

    # Code-behind partials must exist for every shared page (generated or hand-written).
    for key in shared:
        cb = os.path.join(APP_PAGES, pascal(key) + "Page.xaml.cs")
        if not os.path.isfile(cb):
            problems.append(f"app/Pages/{pascal(key)}Page.xaml.cs missing — run `e2e.py gen`")

    if problems:
        print(f"LINT: {len(problems)} problem(s)")
        for p in problems:
            print("  -", p)
        return 1
    print(f"LINT: clean ({len(shared)} shared pages, {len(manifest)} manifest rows)")
    return 0


# ---------------------------------------------------------------- keys ------------------------------
def cmd_keys(args: argparse.Namespace) -> int:
    keys = shared_keys() if args.shared_only else all_keys()
    for k in keys:
        print(k)
    return 0


# ---------------------------------------------------------------- capture ---------------------------
# macCatalyst capture: launch the app bundle in the BACKGROUND (`open -g -n --env ...` — LaunchServices
# launches it WITHOUT activation, so the operator's keyboard/mouse focus is NEVER touched, unlike a
# direct binary exec which self-activates on launch), locate its window by CGWindowID (via
# pyobjc-framework-Quartz — `pip3 install pyobjc-framework-Quartz`), then `screencapture -x -o -l <id>`
# that SPECIFIC window — no `set frontmost`, and no risk of another window (a system notification,
# another app, the operator's own IDE) compositing into the shot, since -l reads that window's own
# backing store regardless of stacking order or occlusion.
#
# FOCUS-STATE RENDERING: a never-activated window renders its CHROME inactive (gray traffic lights /
# title text — already review-exempt) and would ALSO dim default-tinted CONTENT (UIButton's system-blue
# text renders gray, UIKit tintAdjustmentMode Dimmed) — which WOULD corrupt content comparisons. All
# three apps therefore honor MAUI_CAPTURE_TINT_NORMAL=1 (set below): they force
# tintAdjustmentMode=Normal on their window, keeping content pixels identical to the active render
# (see ios/host_run.mm + MauiReference/MauiProgram.cs).
#
# SIGKILL to end (SIGTERM makes .NET apps crash-report a lingering dialog). Falls back to the OLD
# fixed-rect + frontmost + region-grab path (2026-07-05 era) only if Quartz is unavailable or no window
# is found in time — that path steals focus AND has the "wrong window composited" hazard, so always
# eyeball a sample if you ever see it engage (a "(fallback rect ...)" line in the capture log).
MACCAT_APPS = {
    "maui": {
        "bin": os.path.join(REF, "app", "bin", "Debug", "net10.0-maccatalyst", "maccatalyst-arm64",
                            "MauiReference.app", "Contents", "MacOS", "MauiReference"),
        "proc": "MauiReference",
        "rect": "221,33,1024,768",
        "env": lambda key, theme: {"MAUI_COMPARE_PAGE": key,
                                   "MAUI_THEME": "Light" if theme == "light" else "Dark"},
    },
    "cpp": {
        "bin": os.path.join(CPP, "examples", "build-maccatalyst", "gallery", "gallery.app",
                            "Contents", "MacOS", "gallery"),
        "proc": "gallery",
        "rect": "244,59,1024,768",
        "env": lambda key, theme: {"MAUI_SAMPLE_PAGE": key, "MAUI_APPEARANCE": theme},
    },
    "xaml": {
        "bin": os.path.join(CPP, "examples", "build-maccatalyst", "gallery_xaml", "gallery_xaml.app",
                            "Contents", "MacOS", "gallery_xaml"),
        "proc": "gallery_xaml",
        "rect": "244,59,1024,768",
        "env": lambda key, theme: {"MAUI_SAMPLE_PAGE": key, "MAUI_APPEARANCE": theme},
    },
}


def capture_out_path(platform: str, framework: str, key: str, theme: str) -> str:
    """maui -> the maui-reference tree (no framework level); cpp/xaml -> the docs/comparison layout.
    The frozen docs/comparison/captures/<platform>/maui tree is NEVER a destination."""
    if framework == "maui":
        return os.path.join(REF_CAPTURES, platform, f"{key}_{theme}.png")
    return os.path.join(COMP, "captures", platform, framework, f"{key}_{theme}.png")


def _osa(script: str) -> str:
    return subprocess.run(["osascript", "-e", script], capture_output=True, text=True).stdout.strip()


def _find_window_id(pid: int, retries: int = 15, delay: float = 0.3) -> int | None:
    """The owning-PID's frontmost normal-layer on-screen window's CGWindowID, or None. Polls briefly
    since window creation isn't instant after process launch. Requires pyobjc-framework-Quartz
    (pip3 install pyobjc-framework-Quartz) — no extra macOS permission needed (unlike CGWindowListCreateImage,
    plain CGWindowListCopyWindowInfo doesn't require Screen Recording access to see other apps' window
    numbers/bounds/owner, only their *pixel content*, which screencapture -l reads via its own grant)."""
    import Quartz  # local import: optional dependency, only needed for maccatalyst capture

    for _ in range(retries):
        info = Quartz.CGWindowListCopyWindowInfo(Quartz.kCGWindowListOptionOnScreenOnly, Quartz.kCGNullWindowID)
        candidates = [w for w in (info or [])
                     if w.get("kCGWindowOwnerPID") == pid and w.get("kCGWindowLayer") == 0]
        if candidates:
            # Prefer the largest normal-layer window (skips any stray small utility window).
            def area(w):
                b = w.get("kCGWindowBounds", {})
                return b.get("Width", 0) * b.get("Height", 0)
            return int(max(candidates, key=area)["kCGWindowNumber"])
        time.sleep(delay)
    return None


def _launch_background(app: dict, env_pairs: dict[str, str]) -> int | None:
    """Launch the app BUNDLE via `open -g -n --env ...` (LaunchServices background launch — the app is
    never activated, so the operator's keyboard/mouse focus is untouched) and return the NEW process's
    pid, or None. `open` detaches, so the pid is found by diffing `pgrep -x <proc>` before/after."""
    bundle = os.path.abspath(os.path.join(os.path.dirname(app["bin"]), "..", ".."))
    before = set(subprocess.run(["pgrep", "-x", app["proc"]], capture_output=True,
                                text=True).stdout.split())
    cmd = ["open", "-g", "-n"]
    for k, v in env_pairs.items():
        cmd += ["--env", f"{k}={v}"]
    cmd.append(bundle)
    if subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode != 0:
        return None
    for _ in range(40):  # `open` returns before the process registers; poll for the new pid
        now = set(subprocess.run(["pgrep", "-x", app["proc"]], capture_output=True,
                                 text=True).stdout.split())
        fresh = now - before
        if fresh:
            return int(next(iter(fresh)))
        time.sleep(0.25)
    return None


def _maccat_shot(framework: str, key: str, theme: str, settle: float) -> bool:
    app = MACCAT_APPS[framework]
    if not os.path.isfile(app["bin"]):
        print(f"  ! missing binary for {framework}: {app['bin']}")
        return False
    # MAUI_CAPTURE_TINT_NORMAL: all three apps force tintAdjustmentMode=Normal so the never-activated
    # window's CONTENT renders exactly like the active state (see the header comment above).
    env_pairs = dict(app["env"](key, theme), MAUI_CAPTURE_TINT_NORMAL="1")
    pid = _launch_background(app, env_pairs)
    proc = None
    if pid is None:
        # LaunchServices launch failed (sandbox/quarantine/...) — direct binary exec. This DOES
        # self-activate (steals focus for the app's lifetime); loud in the log via the fallback line.
        env = dict(os.environ, **env_pairs)
        proc = subprocess.Popen([app["bin"]], env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        pid = proc.pid
    try:
        time.sleep(settle)
        subprocess.run(["killall", "-9", "ReportCrash"], stderr=subprocess.DEVNULL)
        subprocess.run(["killall", "UserNotificationCenter"], stderr=subprocess.DEVNULL)
        win_id = _find_window_id(pid)
        out = capture_out_path("maccatalyst", framework, key, theme)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        if win_id is not None:
            # -x: no capture-sound. -o: omit the drop-shadow padding (tight window-bounds crop).
            # -l: this specific window, by CGWindowID — reads that window's own backing store, so no
            # OTHER window (a system notification, another app, an IDE) can ever composite into the
            # shot, and the window needs neither focus nor front-of-stack placement.
            rc = subprocess.run(["screencapture", "-x", "-o", "-l", str(win_id), out]).returncode
            ok = rc == 0 and os.path.isfile(out)
            print(f"  {framework:5} {key:28} {'ok' if ok else 'FAIL'} (window {win_id})")
        else:
            # Fallback: no Quartz / no window found — the old fixed-rect + frontmost path (focus steal
            # + wrong-window-composite hazard; eyeball the resulting PNG).
            _osa(f'tell application "System Events" to set frontmost of '
                 f'(first process whose unix id is {pid}) to true')
            time.sleep(1.2)
            rect = app["rect"]
            got = _osa(f'tell application "System Events" to tell process "{app["proc"]}"\n'
                       "set p to position of window 1\nset s to size of window 1\n"
                       'return ((item 1 of p) as string) & "," & ((item 2 of p) as string) & "," & '
                       '((item 1 of s) as string) & "," & ((item 2 of s) as string)\nend tell')
            if got.count(",") == 3:
                rect = got
            rc = subprocess.run(["screencapture", "-x", f"-R{rect}", out]).returncode
            ok = rc == 0 and os.path.isfile(out)
            print(f"  {framework:5} {key:28} {'ok' if ok else 'FAIL'} (fallback rect {rect})")
        return ok
    finally:
        subprocess.run(["kill", "-9", str(pid)], stderr=subprocess.DEVNULL)
        if proc is not None:
            try:
                proc.wait(timeout=3)
            except Exception:
                pass
        time.sleep(0.4)


def _builder_twin_keys() -> set[str] | None:
    """Keys manifest.json marks builder_twin:false have NO code-first page in the `gallery` app — its
    MAUI_SAMPLE_PAGE dispatch (main.cpp make_selected_page) silently falls back to value_controls for an
    unrecognized name, so capturing "cpp" for one of these keys previously produced a MISLEADING
    wrong-page screenshot instead of skipping. Returns None (no filtering) if the manifest is empty/absent
    — all keys are treated as having a cpp twin, matching the old behavior for legacy/pre-manifest setups."""
    manifest = load_manifest()
    if not manifest:
        return None
    return {row["key"] for row in manifest if row.get("builder_twin", True)}


def cmd_capture(args: argparse.Namespace) -> int:
    if args.platform != "maccatalyst":
        print(f"error: platform {args.platform!r} not absorbed yet — use the legacy scripts under "
              "port/cpp/tools/parity/ (capture_all.py for ios, build_android_apphost*.sh + "
              "capture_all_csharp_android.sh for android, capture_appkit.py for appkit)")
        return 2
    frameworks = [f for f in args.framework.split(",") if f in MACCAT_APPS]
    themes = [t for t in args.theme.split(",") if t in ("light", "dark")]
    keys = args.keys or shared_keys()
    if not keys:
        print("no keys to capture (no shared pages yet and none given)")
        return 2
    twin_keys = _builder_twin_keys()
    print(f"capture maccatalyst: {len(keys)} key(s) x {frameworks} x {themes}")
    failures, skipped = 0, 0
    for theme in themes:
        for key in keys:
            for fw in frameworks:
                if fw == "cpp" and twin_keys is not None and key not in twin_keys:
                    print(f"  cpp   {key:28} skip (builder_twin:false — no code-first page)")
                    skipped += 1
                    continue
                if not _maccat_shot(fw, key, theme, args.settle):
                    failures += 1
    print(f"done ({failures} failure(s), {skipped} skipped)")
    return 1 if failures else 0


# ---------------------------------------------------------------- board -----------------------------
THEMES = ("light", "dark")
PLATFORM_FW = {
    "ios": ("maui", "cpp", "xaml"),
    "maccatalyst": ("maui", "cpp", "xaml", "appkit_cpp", "appkit_xaml"),
    "android": ("maui", "cpp", "xaml"),
}
EMPTY_REVIEW = {"status": None, "review": ""}


def _board_shot_path(platform: str, fw: str, key: str, theme: str) -> str | None:
    """comparison.json-relative screenshot path, or None. maui is DUAL-ROOT: the mutable
    maui-reference tree first, then the frozen historical docs/comparison tree."""
    if fw == "maui":
        for ext in ("gif", "png"):
            if os.path.isfile(os.path.join(REF_CAPTURES, platform, f"{key}_{theme}.{ext}")):
                return f"../../../maui-reference/captures/{platform}/{key}_{theme}.{ext}"
    for ext in ("gif", "png"):
        rel = f"captures/{platform}/{fw}/{key}_{theme}.{ext}"
        if os.path.isfile(os.path.join(COMP, rel)):
            return rel
    return None


def cmd_board(_args: argparse.Namespace) -> int:
    prev = {}
    if os.path.isfile(COMP_JSON):
        prev = {r["name"]: r for r in json.load(open(COMP_JSON, encoding="utf-8"))}

    review_slots = ("sonnet", "gemini", "sonnet_xaml", "gemini_xaml", "pixel", "pixel_xaml")
    data, real = [], 0
    for key in all_keys():
        old = prev.get(key, {})
        old_plats = old.get("platforms", {})
        page = {
            "name": key,
            "title": old.get("title") or " ".join(w.capitalize() for w in key.split("_")),
            "description": old.get("description", ""),
            "platforms": {},
        }
        for plat, fws in PLATFORM_FW.items():
            shots = {}
            for fw in fws:
                shots[fw] = {}
                for theme in THEMES:
                    p = _board_shot_path(plat, fw, key, theme)
                    shots[fw][theme] = p
                    real += p is not None
            entry = {"screenshots": shots}
            old_plat = old_plats.get(plat, {})
            for slot in review_slots:
                if slot in old_plat:
                    entry[slot] = old_plat[slot]
                elif slot in ("sonnet", "gemini"):
                    entry[slot] = dict(EMPTY_REVIEW)
            page["platforms"][plat] = entry
        data.append(page)

    json.dump(data, open(COMP_JSON, "w", encoding="utf-8"), indent=2)
    print(f"wrote comparison.json: {len(data)} pages, {real} real screenshot cells")
    gen_readme = os.path.join(COMP, "tools", "gen_readme.py")
    if os.path.isfile(gen_readme):
        return subprocess.run([sys.executable, gen_readme]).returncode
    return 0


# ---------------------------------------------------------------- pixel -----------------------------
def cmd_pixel(args: argparse.Namespace) -> int:
    # Absorbed from port/cpp/tools/parity/pixel_score.py (parity ruling 5's four comparisons). The
    # legacy script resolves the maui column only against docs/comparison; this version follows the
    # comparison.json relative paths (which cmd_board writes dual-root), so it works for both trees.
    try:
        import numpy as np  # noqa: F401
        from PIL import Image  # noqa: F401
    except ImportError as exc:
        print(f"error: `pixel` needs Pillow + numpy ({exc})")
        return 2

    sys.path.insert(0, os.path.join(CPP, "tools", "parity"))
    import pixel_score  # the shared implementation (deleted in P4 once fully absorbed)

    pages = json.load(open(COMP_JSON, encoding="utf-8"))
    want = set(k.strip() for k in args.only.split(",") if k.strip()) if args.only else None
    slots = [("cpp", "pixel"), ("xaml", "pixel_xaml")]
    scored = 0
    for page in pages:
        if want is not None and page["name"] not in want:
            continue
        for plat, platform in page["platforms"].items():
            sc = platform["screenshots"]
            maui = sc.get("maui", {})
            themes = THEMES if plat != "android" else ("light",)
            for fw, slot in slots:
                other = sc.get(fw, {})
                theme_scores = {t: pixel_score.score_theme(maui.get(t), other.get(t)) for t in themes}
                status, review = pixel_score.classify(theme_scores)
                platform[slot] = {"status": status, "review": review}
                scored += 1
    json.dump(pages, open(COMP_JSON, "w", encoding="utf-8"), indent=2)
    print(f"scored {scored} page x platform x framework comparisons")
    return 0


# ------------------------------------------------------------ consistency ---------------------------
def cmd_consistency(args: argparse.Namespace) -> int:
    """Mechanical cross-check for the "both green but visually different" contradiction: a page whose
    cpp and xaml columns are BOTH judged to match the same MAUI ground truth (sonnet/sonnet_xaml both
    "green") cannot simultaneously look substantially different from EACH OTHER — if they do, at least
    one of those two verdicts must be wrong (or the two captures are non-deterministic/stale). This
    reuses pixel_score's SSIM/diff%% machinery directly on the cpp<->xaml pair (no MAUI involved), and
    writes a "consistency" slot alongside sonnet/gemini/pixel so gen_readme.py can surface it.

    This does not replace human/vision judgment of comparisons 1-4 (ruling 5) — it is a cheap, always-on
    guardrail that catches the specific self-contradiction a reviewer (human, Sonnet, or Gemini) can
    slip into when comparisons 1-4 are judged independently per column instead of against each other.
    """
    try:
        import numpy as np  # noqa: F401
        from PIL import Image  # noqa: F401
    except ImportError as exc:
        print(f"error: `consistency` needs Pillow + numpy ({exc})")
        return 2

    sys.path.insert(0, os.path.join(CPP, "tools", "parity"))
    import pixel_score

    pages = json.load(open(COMP_JSON, encoding="utf-8"))
    want = set(k.strip() for k in args.only.split(",") if k.strip()) if args.only else None
    flagged = []
    checked = 0
    for page in pages:
        if want is not None and page["name"] not in want:
            continue
        for plat, platform in page["platforms"].items():
            sc = platform["screenshots"]
            cpp, xaml = sc.get("cpp", {}), sc.get("xaml", {})
            themes = THEMES if plat != "android" else ("light",)
            theme_scores = {t: pixel_score.score_theme(cpp.get(t), xaml.get(t)) for t in themes}
            have = {t: v for t, v in theme_scores.items() if v is not None}
            if not have:
                continue  # no comparable cpp/xaml pair on this platform — nothing to cross-check
            checked += 1
            worst_ssim = min(v["ssim"] for v in have.values())
            worst_diff = max(v["diff_pct"] for v in have.values())
            cpp_xaml_differ = not (worst_ssim >= 0.98 and worst_diff <= 1.0)

            both_green = (
                platform.get("sonnet", {}).get("status") == "green"
                and platform.get("sonnet_xaml", {}).get("status") == "green"
            )
            if both_green and cpp_xaml_differ:
                parts = [f"{t.capitalize()}: SSIM {v['ssim']:.4f}, {v['diff_pct']:.2f}% pixels differ"
                         for t, v in have.items()]
                review = ("cpp and xaml both marked green vs MAUI, but differ from EACH OTHER ("
                           + " · ".join(parts) + ") — at least one verdict needs re-review.")
                platform["consistency"] = {"status": "flag", "review": review}
                flagged.append((page["name"], plat, review))
            else:
                platform["consistency"] = {"status": "ok", "review": ""}

    json.dump(pages, open(COMP_JSON, "w", encoding="utf-8"), indent=2)
    print(f"checked {checked} page x platform cpp/xaml pairs; {len(flagged)} contradiction(s) flagged")
    for name, plat, review in flagged:
        print(f"  FLAG {name} [{plat}]: {review}")
    return 1 if flagged and args.strict else 0


# ---------------------------------------------------------------- main ------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(prog="e2e.py", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_gen = sub.add_parser("gen", help="regenerate C++ TU wrappers + MAUI code-behind partials")
    p_gen.add_argument("--embed-mode", choices=("embed", "bytes"), default="embed",
                       help="embed: #embed TUs into Views/ (checked-in form). "
                            "bytes: android byte-array TUs into --out-dir (NDK Clang 18 has no #embed).")
    p_gen.add_argument("--out-dir", default=None, help="output dir for --embed-mode=bytes")
    p_gen.set_defaults(fn=cmd_gen)

    p_lint = sub.add_parser("lint", help="authoring-rule checks over pages/*.xaml + manifest.json")
    p_lint.set_defaults(fn=cmd_lint)

    p_keys = sub.add_parser("keys", help="print the canonical page-key set")
    p_keys.add_argument("--shared-only", action="store_true",
                        help="only keys migrated to pages/ (exclude legacy Views twins)")
    p_keys.set_defaults(fn=cmd_keys)

    p_cap = sub.add_parser("capture", help="screenshot capture (maccatalyst absorbed; others legacy)")
    p_cap.add_argument("--platform", default="maccatalyst",
                       choices=("ios", "maccatalyst", "android", "appkit"))
    p_cap.add_argument("--framework", default="maui,cpp,xaml",
                       help="comma list of maui,cpp,xaml (default all three)")
    p_cap.add_argument("--theme", default="light,dark", help="comma list of light,dark")
    p_cap.add_argument("--settle", type=float, default=float(os.environ.get("MAUI_SETTLE", "4.0")),
                       help="seconds to wait after launch before the shot")
    p_cap.add_argument("keys", nargs="*", help="page keys (default: all shared pages)")
    p_cap.set_defaults(fn=cmd_capture)

    p_board = sub.add_parser("board", help="rescan captures -> comparison.json -> README.md")
    p_board.set_defaults(fn=cmd_board)

    p_pixel = sub.add_parser("pixel", help="SSIM/diff%% scorer (ruling-5 four comparisons)")
    p_pixel.add_argument("--only", default="", help="comma-separated page keys (default: all)")
    p_pixel.set_defaults(fn=cmd_pixel)

    p_cons = sub.add_parser("consistency", help="flag green/green pages whose cpp and xaml differ")
    p_cons.add_argument("--only", default="", help="comma-separated page keys (default: all)")
    p_cons.add_argument("--strict", action="store_true", help="exit 1 if any contradiction is flagged")
    p_cons.set_defaults(fn=cmd_consistency)

    args = parser.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
