#!/usr/bin/env python3
"""e2e.py — THE unified tool for the MAUI-vs-C++-port end-to-end verification loop.

One entrypoint, subcommands for every deterministic step of the loop (see
port/maui-reference/docs/VERIFICATION_LOOP.md for the full 10-step protocol this tool serves, and
README.md next to this file for per-subcommand usage). It progressively absorbs the legacy script zoo
under port/cpp/tools/parity/ and port/cpp/docs/comparison/tools/ — each legacy script is deleted once
its subcommand replaces it.

Data model (the "naming triple", lint-enforced): a page key like `activity_indicator` maps to
    port/maui-reference/pages/activity_indicator.xaml            (THE canonical shared markup)
    x:Class="MauiReference.Pages.ActivityIndicatorPage"          (MAUI code-behind partial class)
    examples::Views::activity_indicator_page()                   (C++ port page factory)
The same .xaml bytes are compiled by real MAUI (XamlC + code-behind) and #embed-ded by the port's
gallery_xaml app — one file, two frameworks, zero divergence.

Subcommands implemented so far:
    gen     regenerate the C++ TU wrappers (.xaml.hpp/.xaml.cpp + gallery_pages.hpp aggregator) AND the
            trivial MAUI code-behind partials from pages/*.xaml. Transitional: pages still living as
            local gallery_xaml/Views/*.xaml twins keep their old-style TUs; a shared page SUPERSEDES a
            same-named local twin (migration = add pages/<k>.xaml, delete Views/<k>.xaml, re-run gen).
    lint    authoring-rule checks over pages/*.xaml + manifest.json (see AUTHORING.md).
    keys    print the canonical page-key set (from pages/*.xaml [+ legacy Views twins during migration]).

Planned (see README): capture, record, pixel, vision, board, catalog, judge.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

# ---------------------------------------------------------------- paths -----------------------------
HERE = os.path.dirname(os.path.abspath(__file__))           # port/tools/e2e
PORT = os.path.normpath(os.path.join(HERE, "..", ".."))     # port/
REF = os.path.join(PORT, "maui-reference")
PAGES = os.path.join(REF, "pages")                          # canonical shared XAML
MANIFEST = os.path.join(PAGES, "manifest.json")
APP_PAGES = os.path.join(REF, "app", "Pages")               # MAUI code-behind partials
CPP = os.path.join(PORT, "cpp")
GALLERY_XAML = os.path.join(CPP, "examples", "gallery_xaml")
VIEWS = os.path.join(GALLERY_XAML, "Views")                 # C++ TU wrappers (+ legacy local twins)

# #embed path from a TU in Views/ to the shared pages dir (resolved relative to the including file,
# like a quoted #include): Views -> gallery_xaml -> examples -> cpp -> port -> maui-reference/pages.
EMBED_REL = "../../../../maui-reference/pages"

GENERATED_MARK = "GENERATED by port/tools/e2e/e2e.py"


def pascal(key: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in key.split("_") if w)


def shared_keys() -> list[str]:
    if not os.path.isdir(PAGES):
        return []
    return sorted(os.path.splitext(f)[0] for f in os.listdir(PAGES) if f.endswith(".xaml"))


def legacy_keys() -> list[str]:
    """Local gallery_xaml/Views twins not yet migrated to the shared pages dir."""
    if not os.path.isdir(VIEWS):
        return []
    return sorted(
        os.path.splitext(f)[0]
        for f in os.listdir(VIEWS)
        if f.endswith(".xaml") and not f.endswith((".xaml.hpp", ".xaml.cpp"))
    )


def all_keys() -> list[str]:
    return sorted(set(shared_keys()) | set(legacy_keys()))


def load_manifest() -> list[dict]:
    if not os.path.isfile(MANIFEST):
        return []
    with open(MANIFEST, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------- gen: C++ TU templates -------------
HPP = '''#pragma once
// {name}.xaml.hpp — page-construction declaration for the `{name}` page (the C++ analog of a .xaml.cs
// partial's generated factory). Bodyless on purpose: the #embed and the build_page call live in the
// sibling translation unit {name}.xaml.cpp, so main.cpp depends only on this declaration.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include <memory>

#include "maui/controls/content_page.hpp"

namespace examples::Views
{{
    [[nodiscard]] std::unique_ptr<maui::controls::content_page> {name}_page();
}} // namespace examples::Views
'''

# Shared-page TU: #embed points OUT of the repo's cpp tree at the canonical maui-reference/pages file,
# and static_asserts compile-time-lock the naming triple (file <-> key <-> x:Class).
CPP_SHARED = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// This TU OWNS the compile-time XAML: the COMPILER embeds the CANONICAL SHARED page
// port/maui-reference/pages/{name}.xaml — the exact same bytes real .NET MAUI compiles via XamlC +
// code-behind (MauiReference.Pages.{pascal}Page) — and build_page hydrates it through the runtime
// loader into a fresh page_impl<no_view_model>. One file, two frameworks, zero divergence.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include <cstddef>
#include <string_view>

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file, like a quoted
    // #include). The two-line embed is the canonical form (a #embed directive cannot live inside a
    // macro body — see fixed_string.hpp).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{embed_rel}/{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};

    // Compile-time naming-triple lock: the embedded bytes must be a ContentPage whose x:Class matches
    // this page's key-derived MAUI partial class (the lint's runtime check, enforced by the compiler).
    template <std::size_t N>
    constexpr bool bytes_contain(const unsigned char (&hay)[N], std::string_view needle)
    {{
        if (needle.empty() || N < needle.size())
        {{
            return needle.empty();
        }}
        for (std::size_t i = 0; i + needle.size() <= N; i++)
        {{
            bool match = true;
            for (std::size_t j = 0; j < needle.size(); j++)
            {{
                if (static_cast<char>(hay[i + j]) != needle[j])
                {{
                    match = false;
                    break;
                }}
            }}
            if (match)
            {{
                return true;
            }}
        }}
        return false;
    }}
    static_assert(bytes_contain({name}_xaml_bytes, "<ContentPage"));
    static_assert(bytes_contain({name}_xaml_bytes, "x:Class=\\"MauiReference.Pages.{pascal}Page\\""));
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''

# Legacy-twin TU: unchanged from the retired gen_pages.py — local Views/<name>.xaml, no x:Class lock
# (legacy twins predate the shared-page naming triple). Deleted per page as migration proceeds.
CPP_LEGACY = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// LEGACY LOCAL TWIN (pre-migration): embeds the local Views/{name}.xaml, which has not yet moved to the
// canonical shared pages dir (port/maui-reference/pages). Migration: move the markup there (adding
// x:Class per docs/AUTHORING.md), delete Views/{name}.xaml, re-run `e2e.py gen`.
//
// {mark} gen — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, embedded by the compiler (resolved relative to this source file). The two-line
    // embed is the canonical form (a #embed directive cannot live inside a macro body).
    constexpr unsigned char {name}_xaml_bytes[] = {{
#embed "{name}.xaml"
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''

BYTES_CPP = '''// {name}.xaml.cpp — implements examples::Views::{name}_page() (declared in {name}.xaml.hpp).
//
// ANDROID BYTES MODE (e2e.py gen --embed-mode=bytes): the NDK-buildable twin of the checked-in #embed
// form. The NDK's bundled Clang (18 as of NDK 27) does NOT implement C23 #embed, so the markup is
// inlined as a byte-array literal — read from the page's .xaml at generation time — and fed into the
// SAME maui::fixed_string / maui::build_page compile-time-XAML path. Plain C++23; Clang-18 clean.
//
// {mark} gen --embed-mode=bytes — do not edit by hand; re-run the generator instead.

#include "Views/{name}.xaml.hpp"

#include "maui/fixed_string.hpp"
#include "maui/xaml_build.hpp"

namespace
{{
    // The raw markup, inlined as bytes (the #embed-into-array form, but literal so no #embed is needed).
    // Byte count == the .xaml file size with NO trailing NUL, so fixed_string's byte-array ctor deduces
    // fixed_string<file_size> — identical to what #embed would produce for the same file.
    constexpr unsigned char {name}_xaml_bytes[] = {{
{byte_rows}
    }};
    constexpr maui::fixed_string {name}_xaml{{{name}_xaml_bytes}};
}} // namespace

namespace examples::Views
{{
    std::unique_ptr<maui::controls::content_page> {name}_page()
    {{
        // unique_ptr<page_impl<no_view_model>> upcasts to unique_ptr<content_page> on return.
        return maui::build_page<maui::no_view_model, {name}_xaml>();
    }}
}} // namespace examples::Views
'''

AGGREGATOR = '''#pragma once
// gallery_pages.hpp — the single aggregator main.cpp's page switcher consumes. It (1) pulls in every
// per-page factory declaration so examples::Views::<name>_page() resolves, and (2) defines the
// MAUI_XAML_GALLERY_PAGES(X) X-macro — one X(<name>) per page — so the runtime string -> compile-time
// factory dispatch is single-sourced (mirrors the builder gallery's MAUI_GALLERY_PAGES).
//
// {mark} gen — do not edit by hand; re-run the generator when pages change.

{includes}

// One X(<name>) per page; main.cpp expands it to a `selected == "<name>"` -> <name>_page() dispatch.
#define MAUI_XAML_GALLERY_PAGES(X) \\
{xmacro}
'''

CODEBEHIND = '''// {mark} gen — trivial code-behind partial for pages/{name}.xaml. Do not edit: pages needing
// interactivity replace this file with a hand-written partial (drop the GENERATED marker line above so
// the generator leaves it alone) wiring handlers via x:Name fields per docs/AUTHORING.md.
namespace MauiReference.Pages;

public partial class {pascal}Page : ContentPage
{{
    public {pascal}Page()
    {{
        InitializeComponent();
    }}
}}
'''


def _byte_rows(path: str, per_row: int = 16) -> str:
    with open(path, "rb") as fh:
        data = fh.read()
    rows = []
    for i in range(0, len(data), per_row):
        chunk = data[i : i + per_row]
        rows.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(rows) if rows else "        0x00,"


def _clang_format(files: list[str]) -> None:
    clang_format = shutil.which("clang-format")
    if clang_format and files:
        subprocess.run([clang_format, "-i", "--style=file", *files], check=True)
    elif files:
        print("WARNING: clang-format not found — generated files may need formatting before the gate")


def cmd_gen(args: argparse.Namespace) -> int:
    shared = shared_keys()
    legacy = [k for k in legacy_keys() if k not in shared]
    names = sorted(set(shared) | set(legacy))
    if not names:
        print("no pages found (neither shared pages/ nor legacy Views twins) — nothing to generate")
        return 0

    if args.embed_mode == "bytes":
        if not args.out_dir:
            print("error: --embed-mode=bytes requires --out-dir (an android-only build dir, not Views/)")
            return 2
        out_dir = os.path.abspath(args.out_dir)
        if os.path.normpath(out_dir) == os.path.normpath(VIEWS):
            print("error: --out-dir must NOT be Views/ (it would clobber the committed #embed TUs)")
            return 2
        os.makedirs(out_dir, exist_ok=True)
        for name in names:
            src = os.path.join(PAGES if name in shared else VIEWS, name + ".xaml")
            with open(os.path.join(out_dir, name + ".xaml.cpp"), "w") as fh:
                fh.write(BYTES_CPP.format(name=name, byte_rows=_byte_rows(src), mark=GENERATED_MARK))
        print(f"generated {len(names)} bytes-mode TUs into {out_dir} "
              f"({len(shared)} shared, {len(legacy)} legacy)")
        return 0

    written = []
    # C++ TU wrappers (shared pages get the x:Class-locked shared template; legacy twins the old one).
    for name in names:
        with open(os.path.join(VIEWS, name + ".xaml.hpp"), "w") as fh:
            fh.write(HPP.format(name=name, mark=GENERATED_MARK))
        template = CPP_SHARED if name in shared else CPP_LEGACY
        with open(os.path.join(VIEWS, name + ".xaml.cpp"), "w") as fh:
            fh.write(template.format(name=name, pascal=pascal(name), embed_rel=EMBED_REL, mark=GENERATED_MARK))
        written += [os.path.join(VIEWS, name + ".xaml.hpp"), os.path.join(VIEWS, name + ".xaml.cpp")]

    includes = "\n".join(f'#include "Views/{n}.xaml.hpp"' for n in names)
    xmacro = " \\\n".join(f"    X({n})" for n in names)
    agg = os.path.join(VIEWS, "gallery_pages.hpp")
    with open(agg, "w") as fh:
        fh.write(AGGREGATOR.format(includes=includes, xmacro=xmacro, mark=GENERATED_MARK))
    written.append(agg)
    _clang_format(written)

    # MAUI code-behind partials for shared pages (skip hand-written ones — no GENERATED marker).
    os.makedirs(APP_PAGES, exist_ok=True)
    cb_new, cb_kept = 0, 0
    for name in shared:
        cb = os.path.join(APP_PAGES, pascal(name) + "Page.xaml.cs")
        if os.path.isfile(cb):
            with open(cb, encoding="utf-8") as fh:
                if GENERATED_MARK not in fh.read():
                    cb_kept += 1
                    continue  # hand-written interactive partial — leave alone
        with open(cb, "w", encoding="utf-8") as fh:
            fh.write(CODEBEHIND.format(name=name, pascal=pascal(name), mark=GENERATED_MARK))
        cb_new += 1

    print(f"generated {len(names)} C++ TU pairs + gallery_pages.hpp "
          f"({len(shared)} shared, {len(legacy)} legacy) ; "
          f"MAUI code-behinds: {cb_new} generated, {cb_kept} hand-written kept")
    return 0


# ---------------------------------------------------------------- lint ------------------------------
# Event-ish attributes banned in shared XAML (interactivity lives in code-behind via x:Name, so the
# port — which has no event-attribute support — hydrates the identical static tree).
EVENT_ATTRS = (
    "Clicked|Pressed|Released|Tapped|TextChanged|ValueChanged|Toggled|CheckedChanged|SelectedIndexChanged|"
    "SelectionChanged|ItemSelected|ItemTapped|Scrolled|ScrollToRequested|Refreshing|SearchButtonPressed|"
    "DateSelected|TimeSelected|Completed|Unfocused|Focused|Loaded|Unloaded|Appearing|Disappearing|"
    "NavigatedTo|NavigatingFrom|NavigatedFrom|PositionChanged|CurrentItemChanged|RemainingItemsThresholdReached|"
    "SwipeStarted|SwipeChanging|SwipeEnded|DragStarting|DropCompleted|Navigating|Navigated"
)
EVENT_RE = re.compile(r"\b(?:" + EVENT_ATTRS + r')\s*=\s*"')
XCLASS_RE = re.compile(r'x:Class\s*=\s*"([^"]+)"')
X2006 = "http://schemas.microsoft.com/winfx/2006/xaml"


def cmd_lint(_args: argparse.Namespace) -> int:
    problems: list[str] = []
    shared = shared_keys()
    manifest = {row["key"]: row for row in load_manifest()}

    for key in shared:
        path = os.path.join(PAGES, key + ".xaml")
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        rel = os.path.relpath(path, PORT)

        m = EVENT_RE.search(text)
        if m:
            problems.append(f"{rel}: event attribute {m.group(0)!r} — banned; wire via x:Name + code-behind")
        m = XCLASS_RE.search(text)
        if not m:
            problems.append(f"{rel}: missing x:Class (required by the MAUI build)")
        elif m.group(1) != f"MauiReference.Pages.{pascal(key)}Page":
            problems.append(f"{rel}: x:Class={m.group(1)!r} != MauiReference.Pages.{pascal(key)}Page "
                            "(naming triple violated)")
        if X2006 in text:
            problems.append(f"{rel}: uses winfx/2006 x: namespace — standardize on winfx/2009 (AUTHORING.md)")
        if "<ContentPage" not in text:
            problems.append(f"{rel}: root element is not ContentPage")
        if key not in manifest:
            problems.append(f"{rel}: no row in pages/manifest.json")

    for key in manifest:
        if key not in shared:
            problems.append(f"manifest.json: row {key!r} has no pages/{key}.xaml file")

    # Code-behind partials must exist for every shared page (generated or hand-written).
    for key in shared:
        cb = os.path.join(APP_PAGES, pascal(key) + "Page.xaml.cs")
        if not os.path.isfile(cb):
            problems.append(f"app/Pages/{pascal(key)}Page.xaml.cs missing — run `e2e.py gen`")

    if problems:
        print(f"LINT: {len(problems)} problem(s)")
        for p in problems:
            print("  -", p)
        return 1
    print(f"LINT: clean ({len(shared)} shared pages, {len(manifest)} manifest rows)")
    return 0


# ---------------------------------------------------------------- keys ------------------------------
def cmd_keys(args: argparse.Namespace) -> int:
    keys = shared_keys() if args.shared_only else all_keys()
    for k in keys:
        print(k)
    return 0


# ---------------------------------------------------------------- main ------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(prog="e2e.py", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_gen = sub.add_parser("gen", help="regenerate C++ TU wrappers + MAUI code-behind partials")
    p_gen.add_argument("--embed-mode", choices=("embed", "bytes"), default="embed",
                       help="embed: #embed TUs into Views/ (checked-in form). "
                            "bytes: android byte-array TUs into --out-dir (NDK Clang 18 has no #embed).")
    p_gen.add_argument("--out-dir", default=None, help="output dir for --embed-mode=bytes")
    p_gen.set_defaults(fn=cmd_gen)

    p_lint = sub.add_parser("lint", help="authoring-rule checks over pages/*.xaml + manifest.json")
    p_lint.set_defaults(fn=cmd_lint)

    p_keys = sub.add_parser("keys", help="print the canonical page-key set")
    p_keys.add_argument("--shared-only", action="store_true",
                        help="only keys migrated to pages/ (exclude legacy Views twins)")
    p_keys.set_defaults(fn=cmd_keys)

    args = parser.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
